### ISSUE TITLE
请问怎么部署

### ISSUE THREAD

**Issue by caock** [egdw/SyncMusicOnline#1]
请问网站怎么部署，可以写个简单的说明吗？以及这个和SyncMusic的关系，非常感谢！

**Comment by egdw** [comment]
您好哦.这个SyncMusicOnline就是SyncMusic通过npm编译之后的文件.你可以fork项目然后打开gitpage就可以使用了哦.也可以下载下来放在服务器(nginx tomcat apache 等...)当中打开.

**Comment by egdw** [comment]
这个相当于直接编译完了.你放在服务器就可以直接用了.SyncMusic是编译之前的原始代码.
