### ISSUE TITLE
请问怎么使用的啊

### ISSUE THREAD

**Issue by HuShanquan3** [egdw/SyncMusicOnline#2]
我打开网页输入链接，然后出现开始使用就没有然后了。。。

**Comment by egdw** [comment]
暂时没有时间维护,请先我之前搭建好的先吧.
http://egdw.coding.me/SyncMusicForWebSocket/

**Comment by HuShanquan3** [comment]
你回复的好快啊，我试了下，手机网页版和电脑PC版一直前十几秒循环，同步不了呢，大神

**Comment by egdw** [comment]
经测试可以使用.
